### ISSUE TITLE
Symbolization not working with python.wasm

### ISSUE THREAD

**Issue by Pryz** [stealthrocket/wzprof#64]
Using latest `python.wasm` from https://github.com/vmware-labs/webassembly-language-runtimes. 

The result CPU profile:
```
❯ go tool pprof /tmp/profile
Main binary filename not available.
tType: cpu
Time: May 10, 2023 at 3:14pm (MDT)
Duration: 8.09s, Total samples = 626.76s (7749.98%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 626.76s, 100% of 626.76s total
      flat  flat%   sum%        cum   cum%
   626.76s   100%   100%    626.76s   100%  <unknown>
(pprof)
```

Looking a bit deeper it seems that we are not able to properly resolve using DWARF. Either the debug sections are missing data is getting stripped during the compilation of `python.wasm` or we don't interpret the data properly

**Comment by Pryz** [comment]
https://github.com/stealthrocket/wzprof/pull/68 didn't fix the issue:
```
❯ go tool pprof /tmp/profile
Main binary filename not available.
Type: cpu
Time: May 11, 2023 at 7:37pm (MDT)
Duration: 311.56ms, Total samples = 5.10s (1637.42%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 5.10s, 100% of 5.10s total
      flat  flat%   sum%        cum   cum%
     5.10s   100%   100%      5.10s   100%  <unknown>
(pprof)
```

cc @pelletier

**Comment by pelletier** [comment]
There's probably something deeper going on. The only PC ranges found by debug/dwarf in this module are

```
[0 0]
[0 1]
[4294967294 4294967294]
```

**Comment by achille-roussel** [comment]
Two things that may be going on:
- the dwarf debug symbols contain references to the python code, not the interpreter
- the wasm-opt pass modifies the size of the wasm binary which invalidates offsets in the dwarf section
